spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 1234
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  banner:
    location: banner/banner.txt
server:
  error:
    whitelabel:
      enabled: false