spring:
  datasource:
    url: jdbc:postgresql://survey-master-pg-survey-master.e.aivencloud.com:25901/defaultdb?currentSchema=public
    username: survey-master
    password: ENC(RJBWFkQbGlEa7rptxut0QJdNBos5/9wTEcrn6p0v3dPNn0TVfDE/NBbBqnv2hJ8edbJTUXjm1aROVOfTyZ51XA==)
    driverClassName: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  banner:
    location: static/banner/banner.txt
server:
  error:
    whitelabel:
      enabled: false
jasypt:
  encryptor:
    password: ${SECRET_ENCRYPTION_KEY}
    algorithm: PBEWITHHMACSHA512ANDAES_256
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator